### ISSUE TITLE
gene embedding data

### ISSUE THREAD

**Issue by hongruhu** [jkobject/scPRINT#7]
Hi, thanks for building such a framework for single cell studies. I was wondering if the gene embedding derived from ESM2 is invariant for different tasks during optimization? If so, I was wondering if the author would share the gene embedding file (shown in https://github.com/jkobject/scPRINT/blob/main/notebooks/generate_gene_embeddings.ipynb)

thanks

**Comment by jkobject** [comment]
Hi! 

Yes it remains invariant across all tasks. One option is to optimize it during pretraining. 

If you feel you need this file for loading the model, you don't, as the embeddings are also stored in the model weights, you just need to loads the weights like this: 

```python
model = scPrint.load_from_checkpoint(
    '../../data/temp/last.ckpt',
    precpt_gene_emb=None,
)
```

You can also recreate the gene embedding file through this notebook you just shared. just call the function, and it should recreate the file itself 

I will still upload the file and send the link here and on the readme! :) 

Best,

**Comment by jkobject** [comment]
now available here on hugging face: https://huggingface.co/jkobject/scPRINT/tree/main
