### ISSUE TITLE
import error about Django

### ISSUE THREAD

**Issue by hanjun98** [jkobject/scPRINT#8]
Hi, first, Thank you for creating a very robust tool.
I have a problem for importing scprint like this.

`ImproperlyConfigured                      Traceback (most recent call last)
Cell In[2], line 1
----> 1 from scprint import scPrint
      2 from scdataloader import Preprocessor, utils
      3 from scprint.tasks import GNInfer, Embedder, Denoiser, withknn

File [~/mambaforge/envs/scprint/lib/python3.10/site-packages/scprint/__init__.py:3](http://147.47.227.7:8891/lab/workspaces/auto-K/tree/codes/MDS/sc-seq/scprint/~/mambaforge/envs/scprint/lib/python3.10/site-packages/scprint/__init__.py#line=2)
      1 __version__ = "0.0.1"
----> 3 from .model.model import scPrint
      5 # from .data_collator import DataCollator
      6 # from .data_sampler import SubsetsBatchSampler
      7 # from .trainer import (
   (...)
     14 #    test,
     15 # )#

File [~/mambaforge/envs/scprint/lib/python3.10/site-packages/scprint/model/__init__.py:1](http://147.47.227.7:8891/lab/workspaces/auto-K/tree/codes/MDS/sc-seq/scprint/~/mambaforge/envs/scprint/lib/python3.10/site-packages/scprint/model/__init__.py#line=0)
----> 1 from .model import *

File [~/mambaforge/envs/scprint/lib/python3.10/site-packages/scprint/model/model.py:23](http://147.47.227.7:8891/lab/workspaces/auto-K/tree/codes/MDS/sc-seq/scprint/~/mambaforge/envs/scprint/lib/python3.10/site-packages/scprint/model/model.py#line=22)
     21 # from .linear_transformer import FastTransformerEncoderWrapper as FastTransformerEncoder
     22 from . import loss
---> 23 from .utils import simple_masker
     24 from . import utils
     25 from .loss import grad_reverse

File [~/mambaforge/envs/scprint/lib/python3.10/site-packages/scprint/model/utils.py:19](http://147.47.227.7:8891/lab/workspaces/auto-K/tree/codes/MDS/sc-seq/scprint/~/mambaforge/envs/scprint/lib/python3.10/site-packages/scprint/model/utils.py#line=18)
     16 import gc
     17 import json
---> 19 from ..tasks import cell_emb as embbed_task
     20 from ..tasks import grn as grn_task
     21 from ..tasks import denoise as denoise_task

File [~/mambaforge/envs/scprint/lib/python3.10/site-packages/scprint/tasks/__init__.py:1](http://147.47.227.7:8891/lab/workspaces/auto-K/tree/codes/MDS/sc-seq/scprint/~/mambaforge/envs/scprint/lib/python3.10/site-packages/scprint/tasks/__init__.py#line=0)
----> 1 from .grn import *
      2 from .cell_emb import *
      3 from .denoise import *

File [~/mambaforge/envs/scprint/lib/python3.10/site-packages/scprint/tasks/grn.py:1](http://147.47.227.7:8891/lab/workspaces/auto-K/tree/codes/MDS/sc-seq/scprint/~/mambaforge/envs/scprint/lib/python3.10/site-packages/scprint/tasks/grn.py#line=0)
----> 1 from scdataloader import Preprocessor, Collator
      2 from scdataloader.data import SimpleAnnDataset
      4 from bengrn.base import train_classifier

File [~/mambaforge/envs/scprint/lib/python3.10/site-packages/scdataloader/__init__.py:1](http://147.47.227.7:8891/lab/workspaces/auto-K/tree/codes/MDS/sc-seq/scprint/~/mambaforge/envs/scprint/lib/python3.10/site-packages/scdataloader/__init__.py#line=0)
----> 1 from .data import Dataset, SimpleAnnDataset
      2 from .datamodule import DataModule
      3 from .preprocess import Preprocessor

File [~/mambaforge/envs/scprint/lib/python3.10/site-packages/scdataloader/data.py:11](http://147.47.227.7:8891/lab/workspaces/auto-K/tree/codes/MDS/sc-seq/scprint/~/mambaforge/envs/scprint/lib/python3.10/site-packages/scdataloader/data.py#line=10)
      9 from torch.utils.data import Dataset as torchDataset
     10 from typing import Union, Optional, Literal
---> 11 from scdataloader.mapped import MappedCollection
     12 import warnings
     14 from anndata import AnnData

File [~/mambaforge/envs/scprint/lib/python3.10/site-packages/scdataloader/mapped.py:12](http://147.47.227.7:8891/lab/workspaces/auto-K/tree/codes/MDS/sc-seq/scprint/~/mambaforge/envs/scprint/lib/python3.10/site-packages/scdataloader/mapped.py#line=11)
      9 import pandas as pd
     10 from lamindb_setup.core.upath import UPath
---> 12 from lamindb.core.storage._anndata_accessor import (
     13     ArrayType,
     14     ArrayTypes,
     15     GroupType,
     16     GroupTypes,
     17     StorageType,
     18     _safer_read_index,
     19     registry,
     20 )
     22 if TYPE_CHECKING:
     23     from lamindb_setup.core.types import UPathStr

File [~/mambaforge/envs/scprint/lib/python3.10/site-packages/lamindb/core/__init__.py:61](http://147.47.227.7:8891/lab/workspaces/auto-K/tree/codes/MDS/sc-seq/scprint/~/mambaforge/envs/scprint/lib/python3.10/site-packages/lamindb/core/__init__.py#line=60)
      1 """Core library.
      2 
      3 Registries:
   (...)
     57 
     58 """
     60 from lamin_utils._inspect import InspectResult
---> 61 from lnschema_core.models import (
     62     CanValidate,
     63     FeatureValue,
     64     HasFeatures,
     65     HasParams,
     66     HasParents,
     67     IsVersioned,
     68     ParamValue,
     69     Record,
     70     Registry,
     71     TracksRun,
     72     TracksUpdates,
     73 )
     75 from lamindb._curate import (
     76     AnnDataCurator,
     77     CurateLookup,
     78     DataFrameCurator,
     79     MuDataCurator,
     80 )
     81 from lamindb._query_manager import QueryManager

File [~/mambaforge/envs/scprint/lib/python3.10/site-packages/lnschema_core/models.py:69](http://147.47.227.7:8891/lab/workspaces/auto-K/tree/codes/MDS/sc-seq/scprint/~/mambaforge/envs/scprint/lib/python3.10/site-packages/lnschema_core/models.py#line=68)
     65 _TRACKING_READY: bool | None = None
     66 IS_RUN_FROM_IPYTHON = getattr(builtins, "__IPYTHON__", False)
---> 69 class IsVersioned(models.Model):
     70     """Base class for versioned models."""
     72     class Meta:

File [~/mambaforge/envs/scprint/lib/python3.10/site-packages/django/db/models/base.py:129](http://147.47.227.7:8891/lab/workspaces/auto-K/tree/codes/MDS/sc-seq/scprint/~/mambaforge/envs/scprint/lib/python3.10/site-packages/django/db/models/base.py#line=128), in ModelBase.__new__(cls, name, bases, attrs, **kwargs)
    126 app_label = None
    128 # Look for an application configuration to attach the model to.
--> 129 app_config = apps.get_containing_app_config(module)
    131 if getattr(meta, "app_label", None) is None:
    132     if app_config is None:

File [~/mambaforge/envs/scprint/lib/python3.10/site-packages/django/apps/registry.py:260](http://147.47.227.7:8891/lab/workspaces/auto-K/tree/codes/MDS/sc-seq/scprint/~/mambaforge/envs/scprint/lib/python3.10/site-packages/django/apps/registry.py#line=259), in Apps.get_containing_app_config(self, object_name)
    251 def get_containing_app_config(self, object_name):
    252     """
    253     Look for an app config containing a given object.
    254 
   (...)
    258     Return None if the object isn't in any registered app config.
    259     """
--> 260     self.check_apps_ready()
    261     candidates = []
    262     for app_config in self.app_configs.values():

File [~/mambaforge/envs/scprint/lib/python3.10/site-packages/django/apps/registry.py:137](http://147.47.227.7:8891/lab/workspaces/auto-K/tree/codes/MDS/sc-seq/scprint/~/mambaforge/envs/scprint/lib/python3.10/site-packages/django/apps/registry.py#line=136), in Apps.check_apps_ready(self)
    132 from django.conf import settings
    134 # If "not ready" is due to unconfigured settings, accessing
    135 # INSTALLED_APPS raises a more helpful ImproperlyConfigured
    136 # exception.
--> 137 settings.INSTALLED_APPS
    138 raise AppRegistryNotReady("Apps aren't loaded yet.")

File [~/mambaforge/envs/scprint/lib/python3.10/site-packages/django/conf/__init__.py:81](http://147.47.227.7:8891/lab/workspaces/auto-K/tree/codes/MDS/sc-seq/scprint/~/mambaforge/envs/scprint/lib/python3.10/site-packages/django/conf/__init__.py#line=80), in LazySettings.__getattr__(self, name)
     79 """Return the value of a setting and cache it in self.__dict__."""
     80 if (_wrapped := self._wrapped) is empty:
---> 81     self._setup(name)
     82     _wrapped = self._wrapped
     83 val = getattr(_wrapped, name)

File [~/mambaforge/envs/scprint/lib/python3.10/site-packages/django/conf/__init__.py:61](http://147.47.227.7:8891/lab/workspaces/auto-K/tree/codes/MDS/sc-seq/scprint/~/mambaforge/envs/scprint/lib/python3.10/site-packages/django/conf/__init__.py#line=60), in LazySettings._setup(self, name)
     59 if not settings_module:
     60     desc = ("setting %s" % name) if name else "settings"
---> 61     raise ImproperlyConfigured(
     62         "Requested %s, but settings are not configured. "
     63         "You must either define the environment variable %s "
     64         "or call settings.configure() before accessing settings."
     65         % (desc, ENVIRONMENT_VARIABLE)
     66     )
     68 self._wrapped = Settings(settings_module)

ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.`

And my enviroment
`# packages in environment at /mnt/gmi-l1/_90.User_Data/dhthxkr/mambaforge/envs/scprint:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   2.1.0                    pypi_0    pypi
aiobotocore               2.13.2                   pypi_0    pypi
aiohappyeyeballs          2.3.5                    pypi_0    pypi
aiohttp                   3.10.3                   pypi_0    pypi
aioitertools              0.11.0                   pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
anndata                   0.10.8                   pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     4.4.0              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4                    pypi_0    pypi
arboreto                  0.1.6                    pypi_0    pypi
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py310h2372a71_4    conda-forge
array-api-compat          1.8                      pypi_0    pypi
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asciitree                 0.3.3                    pypi_0    pypi
asgiref                   3.8.1                    pypi_0    pypi
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3                    pypi_0    pypi
attridict                 0.0.9                    pypi_0    pypi
attrs                     24.2.0             pyh71513ae_0    conda-forge
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
bengrn                    1.0.2                    pypi_0    pypi
bio                       1.7.1                    pypi_0    pypi
biomart                   0.9.2                    pypi_0    pypi
bionty                    0.48.0                   pypi_0    pypi
biopython                 1.84                     pypi_0    pypi
biothings-client          0.3.1                    pypi_0    pypi
black                     23.12.1                  pypi_0    pypi
bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
bokeh                     3.5.1                    pypi_0    pypi
boltons                   24.0.0                   pypi_0    pypi
botocore                  1.34.131                 pypi_0    pypi
brotli-python             1.1.0           py310hc6cd4ac_1    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cellxgene-census          1.15.0                   pypi_0    pypi
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
cffi                      1.17.0          py310h2fdcea3_0    conda-forge
chardet                   5.2.0                    pypi_0    pypi
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
chex                      0.1.86                   pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.0.0                    pypi_0    pypi
colourmap                 1.1.17                   pypi_0    pypi
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1                    pypi_0    pypi
coverage                  7.6.1                    pypi_0    pypi
ctxcore                   0.2.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
cytoolz                   0.12.3                   pypi_0    pypi
d3graph                   2.5.0                    pypi_0    pypi
dask                      2024.8.0                 pypi_0    pypi
dask-expr                 1.1.10                   pypi_0    pypi
datazets                  0.1.9                    pypi_0    pypi
debugpy                   1.8.5           py310hea249c9_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
decoupler                 1.8.0                    pypi_0    pypi
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
deprecated                1.2.14                   pypi_0    pypi
deprecation               2.1.0                    pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
distributed               2024.8.0                 pypi_0    pypi
dj-database-url           2.2.0                    pypi_0    pypi
django                    5.1                      pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
docrep                    0.3.2                    pypi_0    pypi
docstring-parser          0.16                     pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
fair-esm                  2.0.0                    pypi_0    pypi
fasteners                 0.19                     pypi_0    pypi
fastobo                   0.12.3                   pypi_0    pypi
filelock                  3.15.4                   pypi_0    pypi
flake8                    6.1.0                    pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
frozendict                2.4.4                    pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
gget                      0.28.6                   pypi_0    pypi
ghp-import                2.1.0                    pypi_0    pypi
gitchangelog              3.0.4                    pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.43                   pypi_0    pypi
gotrue                    2.6.2                    pypi_0    pypi
gprofiler-official        1.0.0                    pypi_0    pypi
grnndata                  1.0.1                    pypi_0    pypi
gseapy                    1.1.3                    pypi_0    pypi
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
h5py                      3.11.0                   pypi_0    pypi
hdbscan                   0.8.38.post1             pypi_0    pypi
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  0.17.3                   pypi_0    pypi
httpx                     0.24.1                   pypi_0    pypi
huggingface-hub           0.24.5                   pypi_0    pypi
hydra-core                1.3.2                    pypi_0    pypi
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
igraph                    0.11.6                   pypi_0    pypi
importlib-metadata        8.2.0              pyha770c72_0    conda-forge
importlib_metadata        8.2.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
inflect                   7.3.1                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
interlap                  0.2.7                    pypi_0    pypi
ipykernel                 6.29.5             pyh3099207_0    conda-forge
ipython                   8.26.0             pyh707e725_0    conda-forge
ipywidgets                8.1.3              pyhd8ed1ab_0    conda-forge
ismember                  1.0.5                    pypi_0    pypi
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
isort                     5.13.2                   pypi_0    pypi
jax                       0.4.31                   pypi_0    pypi
jaxlib                    0.4.31                   pypi_0    pypi
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
json5                     0.9.25             pyhd8ed1ab_0    conda-forge
jsonargparse              4.32.0                   pypi_0    pypi
jsonpickle                3.2.2                    pypi_0    pypi
jsonpointer               3.0.0           py310hff52083_0    conda-forge
jsonschema                4.23.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.23.0               hd8ed1ab_0    conda-forge
jupyter                   1.0.0             pyhd8ed1ab_10    conda-forge
jupyter-lsp               2.2.5              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.2              pyhd8ed1ab_0    conda-forge
jupyter_console           6.6.3              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2           py310hff52083_0    conda-forge
jupyter_events            0.10.0             pyhd8ed1ab_0    conda-forge
jupyter_server            2.14.2             pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.5.3              pyhd8ed1ab_0    conda-forge
jupyterlab                4.2.4              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_1    conda-forge
jupyterlab_server         2.27.3             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.11             pyhd8ed1ab_0    conda-forge
keopscore                 2.2.3                    pypi_0    pypi
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5                    pypi_0    pypi
krb5                      1.21.3               h659f571_0    conda-forge
lamin-cli                 0.16.0                   pypi_0    pypi
lamin-utils               0.13.2                   pypi_0    pypi
lamindb                   0.75.1                   pypi_0    pypi
lamindb-setup             0.76.3                   pypi_0    pypi
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
legacy-api-wrap           1.4                      pypi_0    pypi
leidenalg                 0.10.2                   pypi_0    pypi
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libstdcxx-ng              14.1.0               hc0a3c3a_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
lightning                 2.4.0                    pypi_0    pypi
lightning-utilities       0.11.6                   pypi_0    pypi
llvmlite                  0.43.0                   pypi_0    pypi
lnschema-core             0.72.2                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
loompy                    3.0.7                    pypi_0    pypi
louvain                   0.8.2                    pypi_0    pypi
lxml                      5.3.0                    pypi_0    pypi
lz4                       4.3.3                    pypi_0    pypi
markdown                  3.6                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.0.1                    pypi_0    pypi
matplotlib                3.9.2                    pypi_0    pypi
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mccabe                    0.7.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mergedeep                 1.3.4                    pypi_0    pypi
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
mkdocs                    1.6.0                    pypi_0    pypi
mkdocs-get-deps           0.2.0                    pypi_0    pypi
ml-dtypes                 0.4.0                    pypi_0    pypi
more-itertools            10.4.0                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msgpack                   1.0.8                    pypi_0    pypi
multidict                 6.0.5                    pypi_0    pypi
multiprocessing-on-dill   3.5.0a4                  pypi_0    pypi
mygene                    3.2.2                    pypi_0    pypi
mypy                      1.11.1                   pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
mysql-connector-python    8.0.29                   pypi_0    pypi
natsort                   8.4.0                    pypi_0    pypi
nbclient                  0.10.0             pyhd8ed1ab_0    conda-forge
nbconvert                 7.16.4               hd8ed1ab_1    conda-forge
nbconvert-core            7.16.4             pyhd8ed1ab_1    conda-forge
nbconvert-pandoc          7.16.4               hd8ed1ab_1    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
networkx                  3.3                      pypi_0    pypi
notebook                  7.2.1              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.4              pyhd8ed1ab_0    conda-forge
numba                     0.60.0                   pypi_0    pypi
numcodecs                 0.13.0                   pypi_0    pypi
numexpr                   2.10.1                   pypi_0    pypi
numpy                     1.26.4                   pypi_0    pypi
numpy-groupies            0.11.2                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.19.3                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.6.20                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
omnipath                  1.0.8                    pypi_0    pypi
openssl                   3.3.1                h4bc722e_2    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
overrides                 7.7.0              pyhd8ed1ab_0    conda-forge
owlready2                 0.46                     pypi_0    pypi
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2                    pypi_0    pypi
pandoc                    3.3                  ha770c72_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
partd                     1.4.2                    pypi_0    pypi
pathspec                  0.12.1                   pypi_0    pypi
patsy                     0.5.6                    pypi_0    pypi
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.4.0                   pypi_0    pypi
pip                       24.2               pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
plottable                 0.1.5                    pypi_0    pypi
pluggy                    1.5.0                    pypi_0    pypi
pooch                     1.8.2                    pypi_0    pypi
postgrest                 0.13.2                   pypi_0    pypi
powerlaw                  1.5                      pypi_0    pypi
prometheus_client         0.20.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.47             pyha770c72_0    conda-forge
prompt_toolkit            3.0.47               hd8ed1ab_0    conda-forge
pronto                    2.5.5                    pypi_0    pypi
protobuf                  5.27.3                   pypi_0    pypi
psutil                    6.0.0           py310hc51659f_0    conda-forge
psycopg2-binary           2.9.9                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_0    conda-forge
pyarrow                   17.0.0                   pypi_0    pypi
pyarrow-hotfix            0.6                      pypi_0    pypi
pybind11                  2.13.4                   pypi_0    pypi
pycodestyle               2.11.1                   pypi_0    pypi
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pydantic                  2.8.2                    pypi_0    pypi
pydantic-core             2.20.1                   pypi_0    pypi
pydantic-settings         2.4.0                    pypi_0    pypi
pydot                     3.0.1                    pypi_0    pypi
pyflakes                  3.1.0                    pypi_0    pypi
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pykeops                   2.2.3                    pypi_0    pypi
pynndescent               0.5.13                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pyscenic                  0.12.1                   pypi_0    pypi
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    7.4.4                    pypi_0    pypi
pytest-cov                4.1.0                    pypi_0    pypi
python                    3.10.0          h543edf9_3_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-dotenv             1.0.1                    pypi_0    pypi
python-fastjsonschema     2.20.0             pyhd8ed1ab_0    conda-forge
python-graphviz           0.20.3                   pypi_0    pypi
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-louvain            0.16                     pypi_0    pypi
python_abi                3.10                    4_cp310    conda-forge
pytorch-lightning         2.4.0                    pypi_0    pypi
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyvis                     0.3.2                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyyaml-env-tag            0.1                      pypi_0    pypi
pyzmq                     26.1.0          py310h7d2b5bf_0    conda-forge
qtconsole-base            5.5.2              pyha770c72_0    conda-forge
qtpy                      2.4.1              pyhd8ed1ab_0    conda-forge
rapidfuzz                 3.9.6                    pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
realtime                  1.0.6                    pypi_0    pypi
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rich                      13.7.1                   pypi_0    pypi
rich-click                1.8.3                    pypi_0    pypi
rpds-py                   0.20.0          py310h42e942d_0    conda-forge
s3fs                      2024.6.1                 pypi_0    pypi
scanpy                    1.10.2                   pypi_0    pypi
scdataloader              1.0.5                    pypi_0    pypi
scib                      1.1.5                    pypi_0    pypi
scib-metrics              0.5.1                    pypi_0    pypi
scikit-learn              1.5.1                    pypi_0    pypi
scikit-misc               0.5.1                    pypi_0    pypi
scipy                     1.12.0                   pypi_0    pypi
scprint                   1.0.15                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
send2trash                1.8.3              pyh0d859eb_0    conda-forge
sentry-sdk                2.13.0                   pypi_0    pypi
session-info              1.0.0                    pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                72.1.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     5.0.1                    pypi_0    pypi
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
somacore                  1.0.11                   pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
sqlite                    3.46.0               h6d4b2fc_0    conda-forge
sqlparse                  0.5.1                    pypi_0    pypi
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.2                   pypi_0    pypi
stdlib-list               0.10.0                   pypi_0    pypi
storage3                  0.7.7                    pypi_0    pypi
strenum                   0.4.15                   pypi_0    pypi
supabase                  2.2.1                    pypi_0    pypi
supafunc                  0.3.3                    pypi_0    pypi
sympy                     1.13.2                   pypi_0    pypi
tblib                     3.0.0                    pypi_0    pypi
tensorboardx              2.6.2.2                  pypi_0    pypi
tensorly                  0.8.1                    pypi_0    pypi
terminado                 0.18.1             pyh0d859eb_0    conda-forge
texttable                 1.7.0                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tiledb                    0.29.1                   pypi_0    pypi
tiledbsoma                1.11.4                   pypi_0    pypi
tinycss2                  1.3.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.1                   pypi_0    pypi
torch                     2.2.0                    pypi_0    pypi
torchaudio                2.2.0                    pypi_0    pypi
torchdata                 0.7.1                    pypi_0    pypi
torchmetrics              1.4.1                    pypi_0    pypi
torchtext                 0.17.0                   pypi_0    pypi
torchvision               0.17.0                   pypi_0    pypi
tornado                   6.4.1           py310hc51659f_0    conda-forge
tqdm                      4.66.5                   pypi_0    pypi
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
triton                    2.2.0                    pypi_0    pypi
typeguard                 4.3.0                    pypi_0    pypi
types-python-dateutil     2.9.0.20240316     pyhd8ed1ab_0    conda-forge
typeshed-client           2.7.0                    pypi_0    pypi
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2024.1                   pypi_0    pypi
umap-learn                0.5.6                    pypi_0    pypi
universal-pathlib         0.2.2                    pypi_0    pypi
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_1    conda-forge
wandb                     0.17.6                   pypi_0    pypi
wandb-core                0.17.0b11                pypi_0    pypi
watchdog                  4.0.2                    pypi_0    pypi
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
webcolors                 24.8.0             pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.8.0              pyhd8ed1ab_0    conda-forge
websockets                12.0                     pypi_0    pypi
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.11             pyhd8ed1ab_0    conda-forge
wrapt                     1.16.0                   pypi_0    pypi
xyzservices               2024.6.0                 pypi_0    pypi
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.9.4                    pypi_0    pypi
zarr                      2.18.2                   pypi_0    pypi
zeromq                    4.3.5                h75354e8_4    conda-forge
zict                      3.0.0                    pypi_0    pypi
zipp                      3.20.0             pyhd8ed1ab_0    conda-forge
zstandard                 0.23.0          py310h64cae3c_0    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge`

If there is any way to solve this problem, could you let me know?

Thank you!🙏

**Comment by jkobject** [comment]
Hey! Sorry for the issue,


This seems like a weird lamindb issue. Did you create a lamindb account and initialized it properly?

Best,

**Comment by hanjun98** [comment]
Thank you for replying, so faster! 
I didn't think that lamindb is essential for scprint.
Following your advice, I can resolve this problem!
Thank you!!

**Comment by jkobject** [comment]
No worries. It is needed for now to get access to all the ontologies of genes, cell types etc..

**Comment by kavithakrishna1** [comment]
Hi, I was having the same error. I have now created a lamindb account and connected to my environment by running:
`lamin login <email> --key <api_key>`  (with obviously my email and API_key)
And it gave me the successful "logged in with handle ..." message. Is there anything else I need to set up?
